apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
 name: {{ .Values.webapp.name }}
spec:
 scaleTargetRef:
   apiVersion: apps/v1
   kind: Deployment
   name: {{ .Values.webapp.name }}
 minReplicas: 1
 maxReplicas: 10
 targetCPUUtilizationPercentage: 50