name: LENS2 CICD Pipeline

# Start the workflow when any updates are made to the src directory in GitHub
on: 
  push:
    branches:
      - main

jobs:
  build-n-push-container:
    runs-on: self-hosted
    steps:
      - name: Checkout the repo 
        uses: actions/checkout@v4
# We use the current date as the tag for the container image
      - name: Get current date
        id: date
        run: echo "date=$(date +'%Y-%m-%d.%H.%M')" >> $GITHUB_OUTPUT
      - name: Login to Harbor
        run: podman login hub.k8s.ucar.edu -u robot-ncote+lens2 -p ${{ secrets.HARBOR_ROBOT_PW  }}
      - name: Build LENS2 image
        run: podman build --format=docker -t hub.k8s.ucar.edu/ncote/lens2-docker:${{ steps.date.outputs.date }} .
      - name: Build Dask image
        run: podman build --format=docker -f Containerfile.dask -t hub.k8s.ucar.edu/ncote/dask-lens2:${{ steps.date.outputs.date }} .
      - name: Push LENS2 image to Harbor
        run: podman push hub.k8s.ucar.edu/ncote/lens2-docker:${{ steps.date.outputs.date }}
      - name: Push LENS2-Dask image to Harbor
        run: podman push hub.k8s.ucar.edu/ncote/dask-lens2:${{ steps.date.outputs.date }}
      - name: Update Helm values.yaml with App image
        run: |
          sed -i "/lens2-docker/ c\    image: hub.k8s.ucar.edu/ncote/lens2-docker:${{ steps.date.outputs.date }}" lens2-helm/values.yaml
      - name: Update Helm values.yaml with Dask image
        run: |
          sed -i "/dask-lens2/ c\    image: hub.k8s.ucar.edu/ncote\/dask-lens2:${{ steps.date.outputs.date }}" lens2-helm/values.yaml
      - name: Update Helm Chart.yaml
        run: |
          sed -i "/appVersion:/ c\appVersion: ${{ steps.date.outputs.date }}" lens2-helm/Chart.yaml
      - name: Run python script to update version by 1
        run: python3 update_ver.py
      - name: Push changes to GitHub
        run: |
          git config --global user.email "$GITHUB_ACTOR@users.noreply.github.com"
          git config --global user.name "$GITHUB_ACTOR"
          git commit -a -m "Update Helm chart via GH Actions"
          git push -u origin main

